In [4]:
from utils.args import args

ModuleNotFoundError: No module named 'utils.args'

In [2]:
import torch.nn as nn

In [4]:
m = nn.Linear(20, 30)
input = torch.randn(128,5, 20)
output = m(input)
print(output.size())
torch.Size([128, 30])

torch.Size([128, 5, 30])


torch.Size([128, 30])

In [9]:
import torch
import numpy as np


In [14]:
tensor = torch.randn(32,4,512)
ent = torch.special.entr(tensor)
ent.shape

grd_all = nn.ModuleList()
for i in np.arange(0,10):
    grd = nn.Sequential(
        nn.Linear(512,2),
		nn.ReLU(),
        nn.Linear(2, 2)
	)
    grd_all += [grd]


In [13]:
grd[0]

Linear(in_features=10, out_features=2, bias=True)

In [16]:
x = torch.randn([32,4,512])

for i in np.arange(0,10):
    print(grd_all[i](x).shape)

torch.Size([32, 4, 2])
torch.Size([32, 4, 2])
torch.Size([32, 4, 2])
torch.Size([32, 4, 2])
torch.Size([32, 4, 2])
torch.Size([32, 4, 2])
torch.Size([32, 4, 2])
torch.Size([32, 4, 2])
torch.Size([32, 4, 2])
torch.Size([32, 4, 2])


In [19]:
for i in range(3,10):
    print(i)

3
4
5
6
7
8
9


In [50]:
from scipy.stats import entropy 
from torch.special import entr

In [53]:
p = torch.randn([32,4,2])
e = torch.sum(entr(p),axis=1)
e.shape

torch.Size([32, 2])

In [24]:
(entropy,p)

In [48]:
inp = torch.randn([32,4,512])
w = torch.randn([32,1,4])

res = torch.bmm(w,inp)

In [49]:
res.shape

torch.Size([32, 1, 512])

In [55]:
p = torch.tensor([1,1/2,-2])
torch.special.entr(p)

tensor([-0.0000, 0.3466,   -inf])

In [48]:
from torch.autograd import Variable
import numpy as np
a = Variable(torch.rand(1, 4), requires_grad=True)
b = a**2
c = b*2
d = c.mean()
e = c.sum()

In [20]:
r = torch.ones([3,4,5])
w = torch.ones([3,4])
w[:,1] = w[:,1]*2
w[:,2] = w[:,2]*3
w[:,3] = w[:,3]*4

In [21]:
w

tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]])

In [24]:
w.reshape(w.shape[0]*w.shape[1])

tensor([1., 2., 3., 4., 1., 2., 3., 4., 1., 2., 3., 4.])

In [69]:
r = torch.tensor([1,2,3,4,5,6,7,8,9,10,11,12]).reshape([3,4])
r

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [73]:
r2 = r.unsqueeze(2)
r2.shape
r3 = r2.repeat(1,1,5)

In [75]:
r3[:,:,1]

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [76]:
r3+1

tensor([[[ 2,  2,  2,  2,  2],
         [ 3,  3,  3,  3,  3],
         [ 4,  4,  4,  4,  4],
         [ 5,  5,  5,  5,  5]],

        [[ 6,  6,  6,  6,  6],
         [ 7,  7,  7,  7,  7],
         [ 8,  8,  8,  8,  8],
         [ 9,  9,  9,  9,  9]],

        [[10, 10, 10, 10, 10],
         [11, 11, 11, 11, 11],
         [12, 12, 12, 12, 12],
         [13, 13, 13, 13, 13]]])

# Metodo 2


In [62]:
r_all = torch.zeros([3,4,5])
for i in range(0,5):
    r_all[:,:,i] = r

In [66]:
r_all[:,:,1]

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [68]:
r_plain = r_all.reshape(r_all.shape[0]*r_all.shape[1],r_all.shape[2])

In [ ]:
r_plain[0:10,]

In [34]:
import torch

L = 3
N = 5
A = torch.randn(L,L)
A.expand(N, L, L) # specifies new size
A.repeat(N,1,1) # specifies number of copies

tensor([[[-1.1666,  0.7277,  2.5156],
         [ 0.8652, -1.0678,  0.6010],
         [-0.0317,  0.4152,  0.1295]],

        [[-1.1666,  0.7277,  2.5156],
         [ 0.8652, -1.0678,  0.6010],
         [-0.0317,  0.4152,  0.1295]],

        [[-1.1666,  0.7277,  2.5156],
         [ 0.8652, -1.0678,  0.6010],
         [-0.0317,  0.4152,  0.1295]],

        [[-1.1666,  0.7277,  2.5156],
         [ 0.8652, -1.0678,  0.6010],
         [-0.0317,  0.4152,  0.1295]],

        [[-1.1666,  0.7277,  2.5156],
         [ 0.8652, -1.0678,  0.6010],
         [-0.0317,  0.4152,  0.1295]]])

In [35]:
A.shape

torch.Size([3, 3])