In [1]:
from torch import nn
import torch
from torch.autograd import Function
import numpy as np


In [6]:

m = nn.LogSoftmax(dim=0)
input = torch.randn(2, 3)
output = m(input)

In [7]:
input

tensor([[-0.1682,  1.2526, -0.6329],
        [-0.1028,  0.2601, -0.3283]])

In [8]:
torch.exp(output)

tensor([[0.4837, 0.7296, 0.4244],
        [0.5163, 0.2704, 0.5756]])

In [5]:
prob = torch.tensor([[0.8,0.2],[0.3,0.7]])
softmax = nn.Softmax(dim=1)
logsoftmax = nn.LogSoftmax(dim=1)

softmax(softmax(softmax(prob)))

tensor([[0.5361, 0.4639],
        [0.4754, 0.5246]])